spring:
  application:
    name: membership

  datasource:
    url: jdbc:h2:mem:membershipdb
  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
